# Generated by Django 5.1.4 on 2024-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1PredictionWebApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
